### ISSUE TITLE
Bug with git.py on MacOS

### ISSUE THREAD

**Issue by gregoriorobles** [MetricsGrimoire/RepositoryHandler#21]
The latest version of git on MacOS does not match following lines:

Lines 106 - 110
        #  git version 1.7.10.4 // 1.8.4.rc3 // 1.7.12.4 (Apple Git-37)

```
    version = out.replace("git version ", "")
   try:
        self.git_version = tuple([int(i) for i in version.split('.')])
```

line 110 throws an exception where it states that it cannot convert "Mac" to integer.

**Comment by gregoriorobles** [comment]
BTW. The bug has been notified by Alexandre Bergel <alexandre.bergel at me.com> in the SATToSE hands on tutorial I gave on the MetricsGrimoire toolset in Mons. It has been replicated on other Macs in the tutorial.

The solution (small, temporary fix) was to change version (line 108) to version = "1.9.1" manually.

**Comment by sduenas** [comment]
Can we get the output of `git --version` command?
This is related to #20 but I though @andygrunwald already fixed it.

**Comment by andygrunwald** [comment]
See https://github.com/MetricsGrimoire/RepositoryHandler/issues/7 and https://github.com/MetricsGrimoire/RepositoryHandler/blame/master/repositoryhandler/backends/git.py#L106 and https://github.com/MetricsGrimoire/RepositoryHandler/commit/f9e18ebf3cf87796d526b0db0dff8a2f246b7461.

I am running on Mac () as well and installed git via homebrew. My current version:
```sh
$ git --version
git version 2.4.5
```

@gregoriorobles Are you running on master / latest version of RepositoryHandler or on the (outdated) version from pip?

**Comment by gregoriorobles** [comment]
This is the output of git --version:
git version 1.9.3 (Apple Git-50)

It was run on master. I see bug #7 was on the same issue.

**Comment by gregoriorobles** [comment]
Just commited a bug fix. I thought I had not permissions to do so and wanted really to do a pull request. Feel free to revert!

**Comment by sduenas** [comment]
@gregoriorobles It's ok for me. Thanks for the fix.

I close it. Feel free to open it again if you find new errors related to this.
